### ISSUE TITLE
https://github.com/acme.inc/stacks/index.yaml does not exist

### ISSUE THREAD

**Issue by nastacio** [kabanero-io/draft-guide-use-appsody-cli#11]
Maybe this URL was meant as an example, but the text does not make it clear. 
Making that clarification would eliminate the confusion, but still be hard to follow, so I suggest using the actual URL for Kabanero 0.6.0:

https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.0/kabanero-stack-hub-index.yaml

cc @SueChaplain

**Comment by SueChaplain** [comment]
Closing this issue, which is transferred to the new guides repo: https://github.com/kabanero-io/guides/issues/40
This repo will be scheduled for deletion
